### ISSUE TITLE
`pyparsing.ParseException: Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found 'm'  (at char 294), (line:1, col:295)` encountered while attempting to run oml pattern7 query

### ISSUE THREAD

**Issue by capsulecorplab** [capsulecorplab/patternbuffer#2]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/rdflib/graph.py", line 1389, in query
    return result(processor.query(query_object, initBindings, initNs, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/rdflib/plugins/sparql/processor.py", line 77, in query
    parsetree = parseQuery(strOrQuery)
  File "/usr/local/lib/python3.8/dist-packages/rdflib/plugins/sparql/parser.py", line 1536, in parseQuery
    return Query.parseString(q, parseAll=True)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1947, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1937, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4052, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4252, in parseImpl
    raise maxException
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4237, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4052, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1677, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4052, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1681, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 4445, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 1681, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/lib/python3/dist-packages/pyparsing.py", line 2883, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found 'm'  (at char 294), (line:1, col:295)
```
for pythonScript

`from rdflib import Graph; datastore = """/home/kasm-user/oml-tutorial/pattern7-clean.ttl"""; query = """PREFIX oml:        <http://opencaesar.io/oml#> PREFIX base:        <http://opencaesar.io/tutorial/vocabulary/base#> PREFIX mission:     <http://opencaesar.io/tutorial/vocabulary/mission#> SELECT DISTINCT ?r_id ?c_id ?i_id WHERE {   [] a mission:Requirement ;     base:hasIdentifier ?r_id ;     mission:specifies [       a mission:Presents ;           # reified relation       oml:hasSource [    			 # source         base:hasIdentifier ?c_id       ] ;       oml:hasTarget [    			  # target         base:hasIdentifier ?i_id       ]     ] } ORDER BY ?r_id ?c_id ?i_id"""; g = Graph(); g.parse(datastore, format="turtle"); results = g.query(query); result_as_byte_string = results.serialize(format="json"); result_as_json = str(result_as_byte_string, "utf-8"); print(result_as_json)`

![Screenshot from 2022-10-20 11-52-34](https://user-images.githubusercontent.com/14095576/197022398-9a9d4f4a-5972-4ecc-b5da-486fe2ca496e.png)

**Comment by capsulecorplab** [comment]
resolved as per https://github.com/capsulecorplab/patternbuffer/commit/168aa453468e976d32003bb7e1778b0ec560930a
